/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Settings.java
 *
 * Created on Dec 29, 2011, 5:17:00 PM
 */

package form;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.*;
import database.*;
import java.util.ArrayList;


/**
 *
 * @author Michael
 */
public class Settings extends javax.swing.JFrame {

    private JFileChooser fc;
    private Database db;
    private boolean errorCheck;
    
    /** Creates new form Settings */
    public Settings() {
        initComponents();
        fc = new JFileChooser();
        db = new Database();
        errorCheck = false;
    }

   

    public void displayErrorMessage(String message, String title)
    {
        //method to display a popup box w/o write the JOptionPane code
        JOptionPane.showMessageDialog( this,message,title,JOptionPane.ERROR_MESSAGE);
    }

    public void displayPopupMessage(String message, String title)
    {
        JOptionPane.showMessageDialog(this,message,title,JOptionPane.INFORMATION_MESSAGE);
    }

        /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTestLabel = new javax.swing.JLabel();
        cbxErrorLog = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTestLabel.setText("jLabel1");

        cbxErrorLog.setText("Error Log");
        cbxErrorLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxErrorLogActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Load");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxErrorLog)
                    .addComponent(lblTestLabel))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxErrorLog)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        lblTestLabel.getAccessibleContext().setAccessibleName("lblTestLabel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        // promts the name and location of the sql file
        int returnVal = fc.showOpenDialog(Settings.this);
        // if the selection is cancel, get out of here
        if(returnVal != JFileChooser.APPROVE_OPTION)
        {
            return;
        }
            
        //store the file as a variable
        File file = fc.getSelectedFile();

        // initialize the database property
        db = new Database();

        // pass the file in the procedure and read the file.
        readFile(file);

        // <editor-fold defaultstate="collapsed" desc="Read File Original">
           // System.out.println(file.getPath());
/*
            try {
                FileReader fr = new FileReader(file.getPath());
                BufferedReader br = new BufferedReader(fr);
                Table tmpTable = new Table();
                Column tmpColumn = new Column();
                while(br.ready()){
                    String tableCreation = br.readLine();

                    // Get the table name
                    int first = tableCreation.indexOf("\"") + 1;
                    int second = tableCreation.indexOf("\"", first);
                    String tableName = tableCreation.substring(first, second);
                    tmpTable = new Table();
                    tmpTable.setTableName(tableName);
                    //System.out.println("Table Name: " + tableName);
                    while(true)
                    {
                        String tmp = br.readLine().trim();
                        if(tmp.endsWith(";"))
                        {
                            db.addTable(tmpTable);
                            //System.out.println(tmpTable.getTableName());
                            //System.out.println(tmpTable.toString());
                            //Add table to database
                            break;
                        }
                        if(tmp.startsWith("("))
                            continue;
                        if(tmp.startsWith("\""))
                        {
                            tmpColumn = new Column();
                            second = tmp.indexOf("\"", 1);
                            String columnName = tmp.substring(1, second);
                            tmpColumn.setColumnName(columnName);
                            //System.out.println("Column Name: " + columnName);
                            String type = tmp.substring(second+1).trim();
                            //System.out.println(type);
                            index = type.indexOf("(");
                            if(index > 0)
                            {
                                dataType = type.substring(0, index);
                                //System.out.println("Data Type: " + dataType);
                                //there is a size
                            }
                            else
                            {
                                index = type.indexOf(" ");
                                if(index > 0)
                                {
                                    dataType = type.substring(0, index);
                                }
                                else
                                {
                                    index = type.indexOf(",");
                                    if(index > 0)
                                    {
                                        dataType = type.substring(0,index);
                                    }else
                                    {
                                        dataType = type;
                                    }
                                }
                                //System.out.println("Data Type: " + dataType);
                                //there is no size
                            }
                            //Add column to table
                            tmpColumn.setColumnType(dataType);
                            tmpTable.addColumn(tmpColumn);
                            //System.out.println(tmpColumn.toString());
                            //System.out.println("");
                            continue;
                        }
                        if(tmp.startsWith("CONSTRAINT"))
                        {
                            if(tmp.contains("PRIMARY KEY"))
                            {
                                //there is at least 1 primary key
                                first = tmp.indexOf("(")+1;
                                second = tmp.indexOf(")");
                                String primaryKey =  tmp.substring(first, second);
                                String lastKey;
                                lastKey = primaryKey;
                                index = lastKey.indexOf(",");
                                while(index>0)
                                {
                                    String aKey = lastKey.substring(0,index).trim();
                                    lastKey = lastKey.substring(index).trim();
                                    first = aKey.indexOf("\"")+1;
                                    second = aKey.indexOf("\"",first);
                                    aKey = aKey.substring(first, second);
                                    ArrayList<Column> tmpList = tmpTable.getColumn();
                                    for(int i = 0;i<tmpList.size();i++)
                                    {
                                        Column tmpCol = tmpList.get(i);
                                        if(tmpCol.getColumnName().equals(aKey))
                                        {
                                            tmpTable.getColumn().get(i).setPrimaryKey(true);
                                            break;
                                        }
                                    }
                                    index = lastKey.indexOf(",");
                                    //System.out.println("A key");
                                }
                                first = lastKey.indexOf("\"")+1;
                                second = lastKey.indexOf("\"",first);
                                lastKey = lastKey.substring(first, second);

                                ArrayList<Column> tmpList = tmpTable.getColumn();
                                for(int i = 0;i<tmpList.size();i++)
                                {
                                    Column tmpCol = tmpList.get(i);
                                    if(tmpCol.getColumnName().equals(lastKey))
                                    {
                                        tmpTable.getColumn().get(i).setPrimaryKey(true);
                                        break;
                                    }
                                }
                                //System.out.println("Last Key");
                                //System.out.println("Primary Key(s): " + tmp.substring(first, second));

                            }
                        }
                        
                        //System.out.println(tmp);
                    }                    
                    //System.out.println(br.readLine());
                }
                br.close();
                fr.close();
            } catch(FileNotFoundException e){
                //if file not found, display this message
                System.out.println(e.getMessage());
                //System.exit(0);
            } catch(IOException ioe){
                //if something went wrong when reading the file, display this message
                System.out.println(ioe.getMessage());            
                //System.exit(0);
            }
 * */
            // </editor-fold>

        //------------------------------------------------------

        //System.out.println(db.toString());

        //name the file for the package header
        returnVal = fc.showSaveDialog(Settings.this);
        if(returnVal != JFileChooser.APPROVE_OPTION)
        {
            return;
        }

        File file1 = fc.getSelectedFile();
        //File file1 = new File("header.txt");


        //name the file for the package body
        returnVal = fc.showSaveDialog(Settings.this);
        if(returnVal != JFileChooser.APPROVE_OPTION)
        {
            return;
        }

        File file2 = fc.getSelectedFile();
        //File file2 = new File("body.txt");

        writeFiles(file1, file2);

        // <editor-fold defaultstate="collapsed" desc="Write File Orginal">
            /*
            try {
                FileWriter fw = new FileWriter(file2.getPath());
                //FileOutputStream fs = new FileOutputStream(file2.getPath());
                BufferedWriter bw = new BufferedWriter(fw);
                //ObjectOutputStream os = new ObjectOutputStream( fs );
                
                ArrayList<Table> allTables = db.getTable();
                for(int i = 0;i<allTables.size();i++)
                {
                    Table tmpTable = allTables.get(i);
                    System.out.println("Table name: " + tmpTable.getTableName() + "\nLength: " + tmpTable.getTableName().length() + "\n");
                    
                }
                //while
                //os.writeChars(dataType);
                //os.writeObject( roomMap );
                //os.close();
            }
            catch (Exception e){
                System.out.println(e.getMessage());
                //e.printStackTrace();
            }
             *
             */
// </editor-fold>
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cbxErrorLogActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxErrorLogActionPerformed
    {//GEN-HEADEREND:event_cbxErrorLogActionPerformed
        // TODO add your handling code here:
        errorCheck = cbxErrorLog.isSelected();
    }//GEN-LAST:event_cbxErrorLogActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    public void readFile(File filename)
    {
        int index;
        String dataType;
        try {
                FileReader fr = new FileReader(filename.getPath());
                BufferedReader br = new BufferedReader(fr);
                Table tmpTable = new Table();
                Column tmpColumn = new Column();
                while(br.ready()){
                    String tableCreation = br.readLine();

                    if(tableCreation.contains("ALTER TABLE"))
                    {
                        break; //if reach to the alter tables, the rest of the file is foreign key constraints
                    }
                    if(!tableCreation.contains("CREATE TABLE"))
                    {
                        break; // there is no create table and error checking
                    }
                    // Get the table name
                    int first = tableCreation.indexOf("\"") + 1;
                    int second = tableCreation.indexOf("\"", first);
                    String tableName = tableCreation.substring(first, second);
                    tmpTable = new Table();
                    tmpTable.setTableName(tableName);
                    //System.out.println("Table Name: " + tableName);
                    while(true)
                    {
                        String tmp = br.readLine().trim();
                        /*
                        if(tmp.endsWith(";"))
                        {
                            db.addTable(tmpTable);
                            //System.out.println(tmpTable.getTableName());
                            //System.out.println(tmpTable.toString());
                            //Add table to database
                            break;
                        }
                         *
                         */
                        if(tmp.endsWith("/"))
                        {
                            //end of the current table, add to database and exit out
                            db.addTable(tmpTable);
                            break;
                        }
                        if(tmp.startsWith(")"))
                        {
                            //continue the the loop by past the )
                            continue;
                        }
                        if(tmp.startsWith("("))
                        {
                            //need to trim off (
                            tmp = tmp.substring(1).trim();
                            //continue;
                        }
                        if(tmp.startsWith("\""))
                        {
                            //this is use to get the column information
                            tmpColumn = new Column();
                            second = tmp.indexOf("\"", 1);
                            String columnName = tmp.substring(1, second);
                            tmpColumn.setColumnName(columnName);
                            String type = tmp.substring(second+1).trim();
                            index = type.indexOf("(");
                            if(index > 0)
                            {
                                //this column has a data type size
                                dataType = type.substring(0, index);
                            }
                            else
                            {
                                index = type.indexOf(" ");
                                if(index > 0)
                                {
                                    //there are addtional information about this columnn (NOT NULL, DEFAULT, ect)
                                    dataType = type.substring(0, index);
                                }
                                else
                                {
                                    index = type.indexOf(",");
                                    if(index > 0)
                                    {
                                        //use if there is only the data type
                                        dataType = type.substring(0,index);
                                    }else
                                    {
                                        // use if there is only the data type and at the end of the table
                                        dataType = type;
                                    }
                                }
                            }
                            //Add column to table and continue the loop
                            tmpColumn.setColumnType(dataType);
                            tmpTable.addColumn(tmpColumn);                            
                            continue;
                        }
                        if(tmp.startsWith("CONSTRAINT"))
                        {
                            //there is constraint, primary or foreign
                            if(tmp.contains("PRIMARY KEY"))
                            {
                                //there is at least 1 primary key
                                first = tmp.indexOf("(")+1;
                                second = tmp.indexOf(")");
                                String primaryKey =  tmp.substring(first, second);
                                String lastKey;
                                lastKey = primaryKey;
                                index = lastKey.indexOf(",");
                                //chech if there is more than 1 primary key
                                while(index>0)
                                {
                                    //grab the next key
                                    String aKey = lastKey.substring(0,index).trim();
                                    lastKey = lastKey.substring(index).trim();
                                    first = aKey.indexOf("\"")+1;
                                    second = aKey.indexOf("\"",first);
                                    aKey = aKey.substring(first, second);
                                    ArrayList<Column> tmpList = tmpTable.getColumn();
                                    for(int i = 0;i<tmpList.size();i++)
                                    {
                                        //loop through until you find the same column
                                        Column tmpCol = tmpList.get(i);
                                        if(tmpCol.getColumnName().equals(aKey))
                                        {
                                            //set the column as a primary and break
                                            tmpTable.getColumn().get(i).setPrimaryKey(true);
                                            break;
                                        }
                                    }
                                    //check if there is another key
                                    index = lastKey.indexOf(",");
                                }
                                first = lastKey.indexOf("\"")+1;
                                second = lastKey.indexOf("\"",first);
                                lastKey = lastKey.substring(first, second);

                                ArrayList<Column> tmpList = tmpTable.getColumn();
                                for(int i = 0;i<tmpList.size();i++)
                                {
                                    //loop through until you find the same column
                                    Column tmpCol = tmpList.get(i);
                                    if(tmpCol.getColumnName().equals(lastKey))
                                    {
                                        //set the column as  a primary and break out
                                        tmpTable.getColumn().get(i).setPrimaryKey(true);
                                        break;
                                    }
                                }
                            }
                            continue;
                        }
                        //check if there is
                        if(tmp.contains("PRIMARY KEY"))
                        {
                            //there is at least 1 primary key
                            first = tmp.indexOf("(")+1;
                            second = tmp.indexOf(")");
                            String primaryKey =  tmp.substring(first, second);
                            String lastKey;
                            lastKey = primaryKey;
                            index = lastKey.indexOf(",");
                            while(index>0)
                            {
                                String aKey = lastKey.substring(0,index).trim();
                                lastKey = lastKey.substring(index).trim();
                                first = aKey.indexOf("\"")+1;
                                second = aKey.indexOf("\"",first);
                                aKey = aKey.substring(first, second);
                                ArrayList<Column> tmpList = tmpTable.getColumn();
                                for(int i = 0;i<tmpList.size();i++)
                                {
                                    Column tmpCol = tmpList.get(i);
                                    if(tmpCol.getColumnName().equals(aKey))
                                    {
                                        tmpTable.getColumn().get(i).setPrimaryKey(true);
                                        break;
                                    }
                                }
                                index = lastKey.indexOf(",");
                                //System.out.println("A key");
                            }
                            first = lastKey.indexOf("\"")+1;
                            second = lastKey.indexOf("\"",first);
                            lastKey = lastKey.substring(first, second);

                            ArrayList<Column> tmpList = tmpTable.getColumn();
                            for(int i = 0;i<tmpList.size();i++)
                            {
                                Column tmpCol = tmpList.get(i);
                                if(tmpCol.getColumnName().equals(lastKey))
                                {
                                    tmpTable.getColumn().get(i).setPrimaryKey(true);
                                    break;
                                }
                            }
                            continue;
                        }
                    }
                }
                br.close();
                fr.close();
            } catch(FileNotFoundException e){
                //if file not found, display this message
                System.out.println(e.getMessage());
                //System.exit(0);
            } catch(IOException ioe){
                //if something went wrong when reading the file, display this message
                System.out.println(ioe.getMessage());
                //System.exit(0);
            }
    }

    public void writeFiles(File file1, File file2)
    {
        try {
                //set up the writer for package header & body
                FileWriter fw1 = new FileWriter(file1.getPath());
                BufferedWriter bw1 = new BufferedWriter(fw1);

                FileWriter fw2 = new FileWriter(file2.getPath());
                BufferedWriter bw2 = new BufferedWriter(fw2);
                
                //get the tables fromt eh database class item
                ArrayList<Table> allTables = db.getTable();
 
                //cycle through the tables 
                for(int i = 0;i<allTables.size();i++)
                {
                    //bw1 is the header
                    //bw2 is the body;
                    //get the table
                    Table tmpTable = allTables.get(i);
                    //get the column array list
                    ArrayList<Column> tmpColumns = tmpTable.getColumn();
                    String pkgName;
                    
                    //set up to determine which columns are primary keys
                    ArrayList<Column> primaryKeys = new ArrayList<Column>();
                    ArrayList<Column> otherColumn = new ArrayList<Column>();
                    boolean primary = false;
                    
                    
                    for(int j=0;j<tmpColumns.size();j++)
                    {
                        Column tmp = tmpColumns.get(j);
                        
                        if(tmp.isPrimaryKey())
                        {
                            //if it is a primary key add it to the primary list and set primary to true
                            primaryKeys.add(tmp);
                            primary = true;
                        }
                        else
                        {
                            //else,add to the other column
                            otherColumn.add(tmp);
                        }
                    }
                                        
                    if(tmpTable.getTableName().length() > 26)
                    {
                        pkgName = "PKG_" + tmpTable.getTableName().substring(0,26);
                    }
                    else
                    {
                        pkgName = "PKG_" + tmpTable.getTableName();
                    }
                    bw1.write("create or replace PACKAGE \""+pkgName+"\" AS\n");
                    bw2.write("create or replace PACKAGE BODY \""+pkgName+"\" AS\n");

                    //cycle through for each procedures

                    // <editor-fold defaultstate="collapsed" desc="Code for the Select">
                    //select
                    if(primary)
                    {
                        String selectName = "P_S_"+tmpTable.getTableName();
                        String selectStart = "PROCEDURE \"" + selectName + "\"(\n";

                        for(int j = 0; j<primaryKeys.size();j++)
                        {
                            Column tmpCol = primaryKeys.get(j);
                            if(j>0)
                            {
                                selectStart += ",\n";
                            }
                            if(tmpCol.getColumnName().length() > 28)
                            {
                                selectStart += "\tU_" + tmpCol.getColumnName().substring(0, 28) + " IN " + tmpCol.getColumnType();
                            }
                            else
                            {
                                selectStart += "\tU_" + tmpCol.getColumnName() + " IN " + tmpCol.getColumnType();
                            }
                        }
                        for(int j = 0; j<otherColumn.size();j++)
                        {
                            Column tmpCol = otherColumn.get(j);
                            selectStart += ",\n";

                            if(tmpCol.getColumnName().length() > 28)
                            {
                                selectStart += "\tU_" + tmpCol.getColumnName().substring(0, 28) + " OUT " + tmpCol.getColumnType();
                            }
                            else
                            {
                                selectStart += "\tU_" + tmpCol.getColumnName() + " OUT " + tmpCol.getColumnType();
                            }
                        }

                        selectStart += "\n)";

                        //select header
                        bw1.write(selectStart + ";\n\n");

                        //select body
                        bw2.write(selectStart + "\n" + "IS \n" + "BEGIN" + "\n");


                        //where clause
                        String endString = " FROM " + tmpTable.getTableName() + " WHERE ";
                        for(int j = 0; j < primaryKeys.size();j++)
                        {
                            Column tmpCol = primaryKeys.get(j);
                            if(j>0)
                            {
                                endString += " AND ";
                            }
                            endString += tmpCol.getColumnName() + " = ";

                            if(tmpCol.getColumnName().length() > 28)
                            {
                                endString += "U_" + tmpCol.getColumnName().substring(0, 28);
                            }
                            else
                            {
                                endString += "U_" + tmpCol.getColumnName();
                            }

                        }
                        endString += ";\n";
                        String selectString = "";
                        for(int j=0;j<otherColumn.size();j++)
                        {
                             Column tmpCol = otherColumn.get(j);
                             selectString += "\tSELECT " + tmpCol.getColumnName() + " INTO ";
                             if(tmpCol.getColumnName().length() > 28)
                             {
                                 selectString += "U_" + tmpCol.getColumnName().substring(0, 28);
                             }
                             else
                             {
                                 selectString += "U_" + tmpCol.getColumnName();
                             }
                             selectString += endString;
                        }
                        if(errorCheck)
                        {
                            selectString += "\tEXCEPTION WHEN OTHERS THEN\n"
                                    + "\tLOGGER.LOG_ERROR()\n"
                                    + "\t\tRAISE;\n";
                        }
                        bw2.write(selectString);
                        bw2.write("END \"" + selectName + "\";\n\n");

                    }
                    
                    // </editor-fold>

                    // <editor-fold defaultstate="collapsed" desc="Code for the Insert">
                    //insert
                    String insertName = "P_I_"+tmpTable.getTableName();
                    String insertStart = "PROCEDURE \"" + insertName + "\"(\n";
                    for(int j = 0;j<tmpColumns.size();j++)
                    {
                        Column tmpCol = tmpColumns.get(j);
                        if(j > 0)
                        {
                            insertStart += ",\n";
                        }
                        
                        if(tmpCol.getColumnName().length() > 28)
                        {
                            insertStart += "\tU_" + tmpCol.getColumnName().substring(0, 28) + " IN " + tmpCol.getColumnType();
                        }
                        else
                        {
                            insertStart += "\tU_" + tmpCol.getColumnName() + " IN " + tmpCol.getColumnType();
                        }
                        
                    }
                    //cycle through columns
                    insertStart += "\n)";



                    // <editor-fold defaultstate="collapsed" desc="Insert Header">
                    /*
                     * PROCEDURE "P_I_OBR_CAMLP_REQUEST"(
        U_REQUESTID IN NUMBER,
        U_CAM_LP_ID IN NUMBER,
        U_USERID IN NUMBER,
        U_REASON IN VARCHAR2,
        U_APPROVED IN NUMBER,
        U_REJECTIONREASON IN VARCHAR2
    );
                     *
                     */
                    // </editor-fold>
                    bw1.write(insertStart + ";\n\n");

                    // <editor-fold defaultstate="collapsed" desc="Insert Body">
                    /*
                     * PROCEDURE "P_I_OBR_CAMLP_REQUEST"(
        U_REQUESTID IN NUMBER,
        U_CAM_LP_ID IN NUMBER,
        U_USERID IN NUMBER,
        U_REASON IN VARCHAR2,
        U_APPROVED IN NUMBER,
        U_REJECTIONREASON IN VARCHAR2
    )
    IS

    BEGIN
        INSERT INTO OBR_CAMLP_REQUEST(REQUESTID, CAM_LP_ID, USERID, REASON, APPROVED, REJECTIONREASON)
        VALUES(U_REQUESTID, U_CAM_LP_ID, U_USERID, U_REASON, U_APPROVED, U_REJECTIONREASON);

    EXCEPTION WHEN OTHERS THEN
        LOGGER.LOG_ERROR();
        RAISE;
    END "P_I_OBR_CAMLP_REQUEST";
                     */
                    // </editor-fold>

                    bw2.write(insertStart + "\n" + "IS \n" + "BEGIN" + "\n");
                    
                    String insertState1 = "\tINSERT INTO " + tmpTable.getTableName() + "(";
                    String insertState2 = "\tVALUES(";
                                                            
                    //cycle through the columns

                    for(int j = 0;j<tmpColumns.size();j++)
                    {
                        Column tmpCol = tmpColumns.get(j);
                        if(j > 0)
                        {
                            insertState1 += ", ";
                            insertState2 += ", ";
                        }
                        if(tmpCol.getColumnName().length() > 28)
                        {
                            insertState2 += "U_" + tmpCol.getColumnName().substring(0, 28);
                        }
                        else
                        {
                            insertState2 += "U_" + tmpCol.getColumnName();
                        }
                        insertState1 += tmpCol.getColumnName();
                    }
                    
                    
                    //insert
                    bw2.write(insertState1 + ")\n" + insertState2 + ");\n");
                    if(errorCheck)
                    {
                        bw2.write("\tEXCEPTION WHEN OTHERS THEN\n"
                                + "\tLOGGER.LOG_ERROR()\n"
                                + "\t\tRAISE;\n");
                        }
                    bw2.write("END \"" + insertName + "\";\n\n");

                    // </editor-fold>

                    // <editor-fold defaultstate="collapsed" desc="Code for the Update">
                    //update
                    
                    if(primary)
                    {
                        String updateName = "P_U_"+tmpTable.getTableName();
                        String updateStart = "PROCEDURE \"" + updateName + "\"(\n";

                        for(int j = 0;j<tmpColumns.size();j++)
                        {
                            Column tmpCol = tmpColumns.get(j);
                            if(j > 0)
                            {
                                updateStart += ",\n";
                            }

                            if(tmpCol.getColumnName().length() > 28)
                            {
                                updateStart += "\tU_" + tmpCol.getColumnName().substring(0, 28) + " IN " + tmpCol.getColumnType();
                            }
                            else
                            {
                                updateStart += "\tU_" + tmpCol.getColumnName() + " IN " + tmpCol.getColumnType();
                            }

                        }

                        //cycle through columns
                        updateStart += "\n)";

                        //update header
                        bw1.write(updateStart + ";\n\n");

                        //update body
                        bw2.write(updateStart + "\n" + "IS \n" + "BEGIN" + "\n");
                        bw2.write("\tUPDATE " + tmpTable.getTableName() + "\n\t");
                        String updateState = "SET ";
                        for(int j = 0; j < otherColumn.size(); j++)
                        {
                            if(j>0)
                            {
                                updateState += ", ";
                            }
                            updateState += otherColumn.get(j).getColumnName() + " = U_";
                            if(otherColumn.get(j).getColumnName().length()>28)
                            {
                                updateState += otherColumn.get(j).getColumnName().substring(0, 28);
                            }
                            else
                            {
                                updateState += otherColumn.get(j).getColumnName();
                            }
                        }
                        updateState += "\n\t";
                        updateState += "WHERE ";
                        for(int j = 0; j < primaryKeys.size(); j++)
                        {
                            if(j>0)
                            {
                                updateState += " AND ";
                            }
                            updateState += primaryKeys.get(j).getColumnName() + " = U_";
                            if(primaryKeys.get(j).getColumnName().length()>28)
                            {
                                updateState += primaryKeys.get(j).getColumnName().substring(0, 28);
                            }
                            else
                            {
                                updateState += primaryKeys.get(j).getColumnName();
                            }
                        }
                        updateState += ";";
                        bw2.write(updateState + "\n");
                        if(errorCheck)
                        {
                            bw2.write("\tEXCEPTION WHEN OTHERS THEN\n"
                                    + "\tLOGGER.LOG_ERROR()\n"
                                    + "\t\tRAISE;\n");
                        }


                        //bw2.write(insertState1 + ")\n" + insertState2 + ");\n");
                        bw2.write("END \"" + updateName + "\";\n\n");
                    }
                    // </editor-fold>
                    
                    // end of package
                    bw1.write("END \""+pkgName+"\";\n/\n\n");
                    bw2.write("END \""+pkgName+"\";\n/\n\n");

                    //System.out.println("Table name: " + tmpTable.getTableName() + "\nLength: " + tmpTable.getTableName().length() + "\n");
                    //bw2.write("Table name: " + tmpTable.getTableName() + "\nLength: " + tmpTable.getTableName().length() + "\n");

                }
                bw2.close();
                bw1.close();
                fw2.close();
                fw1.close();
            }
            catch (Exception e){
                System.out.println(e.getMessage());
                //e.printStackTrace();
            }
    }

    public void mergeTwoFiles(File file1, File file2, File finalFile)
    {
        try {
                FileWriter fw = new FileWriter(file1.getPath());
                BufferedWriter bw = new BufferedWriter(fw);

                FileReader fr = new FileReader(file1.getPath());
                BufferedReader br = new BufferedReader(fr);

                while(br.ready())
                {
                    bw.write(br.readLine() + "\n");
                }
                br.close();
                fr.close();

                bw.write("\n\n\n");

                fr = new FileReader(file2.getPath());
                br = new BufferedReader(fr);
                while(br.ready())
                {
                    bw.write(br.readLine() + "\n");
                }
                br.close();
                fr.close();

                bw.close();
                fw.close();

            } catch(FileNotFoundException e){
                //if file not found, display this message
                System.out.println(e.getMessage());
                //System.exit(0);
            } catch(IOException ioe){
                //if something went wrong when reading the file, display this message
                System.out.println(ioe.getMessage());
                //System.exit(0);
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxErrorLog;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblTestLabel;
    // End of variables declaration//GEN-END:variables

}
